"use client";
import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import { useRouter } from "next/navigation";
import Image from "next/image";
import type { ArticleRecord, Taxonomy } from "@/types";
import { apiRequest } from "../client-forms";
import { Badge } from "../ui";
const RichEditor = dynamic(() => import("./rich-editor"), { ssr: false, loading: () => <div className="skeleton editor-loading" /> });
export function ArticleEditor({ article, categories, tags, base }: { article?: ArticleRecord; categories: Taxonomy[]; tags: Taxonomy[]; base: string }) {
  const router = useRouter(); const [content, setContent] = useState(article?.content || ""); const [dirty, setDirty] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [alt, setAlt] = useState(article?.coverImage?.alt || "");
  useEffect(() => { const unload = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; const navigate = (event: MouseEvent) => { if (dirty && event.target instanceof Element && event.target.closest("a[href]") && !window.confirm("Leave this page? Your unsaved changes will be lost.")) event.preventDefault(); }; window.addEventListener("beforeunload", unload); document.addEventListener("click", navigate, true); return () => { window.removeEventListener("beforeunload", unload); document.removeEventListener("click", navigate, true); }; }, [dirty]);
  async function upload(file: File) {
    if (!article) return; if (dirty) { setError("Save your changes before uploading an image."); return; } setBusy(true); setError("");
    try { const response = await fetch(`/api/articles/${article._id}/cover`, { method: "POST", headers: { "Content-Type": file.type, "X-Image-Alt": encodeURIComponent(alt), "X-Article-Revision": String(article.revision) }, body: file }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Image upload failed"); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Image upload failed"); } finally { setBusy(false); }
  }
  return <form className="editor-layout" onChange={event => { if (!(event.target instanceof HTMLInputElement && event.target.type === "file")) setDirty(true); }} onSubmit={async event => { event.preventDefault(); setBusy(true); setError(""); setMessage(""); const form = new FormData(event.currentTarget); const data = { ...Object.fromEntries(form), content, category: form.get("category") || null, tags: form.getAll("tags"), revision: article?.revision, coverAlt: alt }; try { const result = await apiRequest(article ? `/api/articles/${article._id}` : "/api/articles", article ? "PATCH" : "POST", data); setDirty(false); setMessage("Article saved"); if (!article) router.replace(`${base}/articles/${result.id}/edit`); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save article"); } finally { setBusy(false); } }}>
    <div className="editor-main panel"><div className="editor-topline"><span className="eyebrow">YOUR STORY</span><Badge status={article?.status || "DRAFT"} /></div><label>Article title<input className="title-input" name="title" defaultValue={article?.title} placeholder="Give your story a strong headline" required minLength={3} maxLength={200} /></label><label>Excerpt<textarea name="excerpt" defaultValue={article?.excerpt} placeholder="The essential idea, in a sentence or two." maxLength={400} rows={3} /></label><label className="editor-label">Article body</label><RichEditor content={content} onChange={html => { setContent(html); setDirty(true); }} /><div className="save-bar"><span className="muted small">{dirty ? "Unsaved changes" : message || "All changes saved"}</span><button className="button" disabled={busy}>{busy ? "Saving…" : article ? "Save changes" : "Save draft"}</button></div>{error ? <p className="notice error" role="alert">{error}</p> : null}{message ? <p className="sr-only" role="status">{message}</p> : null}</div>
    <aside className="editor-settings"><div className="panel form-stack"><h3>Story settings</h3><label>Category<select name="category" defaultValue={article?.category?._id || ""}><option value="">Choose a category</option>{categories.map(c => <option key={c._id} value={c._id}>{c.name}{!c.isActive ? " (inactive)" : ""}</option>)}</select></label><fieldset><legend>Tags</legend><div className="tag-options">{tags.map(tag => <label className="checkbox" key={tag._id}><input type="checkbox" name="tags" value={tag._id} defaultChecked={article?.tags.some(t => t._id === tag._id)} />{tag.name}</label>)}</div></fieldset><label>Slug<input name="slug" defaultValue={article?.slug} placeholder="Generated from your title" pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={120} /></label></div>
    <div className="panel form-stack"><h3>Cover image</h3>{article?.coverImage ? <Image className="cover-preview" src={article.coverImage.secureUrl} alt={article.coverImage.alt} width={600} height={340} /> : <div className="image-empty">Add a visual to your story</div>}<label>Image description<input value={alt} onChange={e => setAlt(e.target.value)} maxLength={250} /></label>{article ? <><label className="file-label">Upload / replace image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={busy} onChange={e => { const file = e.target.files?.[0]; if (file) void upload(file); e.target.value = ""; }} /></label><p className="muted small">JPEG, PNG, WebP, AVIF · Up to 5 MB. Save edits before uploading.</p>{article.coverImage ? <button className="button danger secondary" type="button" disabled={busy || dirty} onClick={async () => { if (!window.confirm("Remove this cover image?")) return; setBusy(true); try { await apiRequest(`/api/articles/${article._id}/cover`, "DELETE", { revision: article.revision }); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to remove image"); } finally { setBusy(false); } }}>Remove image</button> : null}</> : <p className="small muted">Save your draft to upload a cover image.</p>}</div>
    <details className="panel form-stack"><summary>Search & social settings</summary><label>SEO title<input name="seoTitle" defaultValue={article?.seoTitle} maxLength={70} /></label><label>Meta description<textarea name="seoDescription" defaultValue={article?.seoDescription} maxLength={170} /></label><label>Canonical URL<input name="canonicalUrl" type="url" defaultValue={article?.canonicalUrl} /></label><label>Social image URL<input name="socialImage" type="url" defaultValue={article?.socialImage} placeholder="https://res.cloudinary.com/…" /></label></details><details className="panel form-stack"><summary>Source attribution</summary><label>Source name<input name="sourceName" defaultValue={article?.sourceName} maxLength={120} /></label><label>Source URL<input name="sourceUrl" type="url" defaultValue={article?.sourceUrl} /></label></details></aside>
  </form>;
}
