"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import dynamic from "next/dynamic";
import { useRouter } from "next/navigation";
import Image from "next/image";
import type { ArticleRecord, Taxonomy } from "@/types";
import { apiRequest } from "../client-forms";
import { Badge } from "../ui";
import { uploadCover } from "./upload";
const RichEditor = dynamic(() => import("./rich-editor"), { ssr: false, loading: () => <div className="skeleton editor-loading" /> });
type Snapshot = { title: string; excerpt: string; slug: string; seoTitle: string; seoDescription: string; category: string };
const textLength = (html: string) => html.replace(/<[^>]*>/g, " ").replace(/&[a-z#0-9]+;/gi, " ").replace(/\s+/g, " ").trim().length;
const siteHost = (process.env.NEXT_PUBLIC_SITE_URL || "https://signal.example").replace(/^https?:\/\//, "").replace(/\/$/, "");
export function ArticleEditor({ article, categories, tags, base, admin = false }: { article?: ArticleRecord; categories: Taxonomy[]; tags: Taxonomy[]; base: string; admin?: boolean }) {
  const router = useRouter(); const form = useRef<HTMLFormElement>(null); const saving = useRef(false);
  const [content, setContent] = useState(article?.content || ""); const [dirty, setDirty] = useState(false); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [alt, setAlt] = useState(article?.coverImage?.alt || ""); const [dragging, setDragging] = useState(false);
  // Revisions only grow, so the newest of the server prop and our own last save is current.
  const [savedRevision, setSavedRevision] = useState(article?.revision ?? 0); const revision = Math.max(article?.revision ?? 0, savedRevision);
  const [snap, setSnap] = useState<Snapshot>({ title: article?.title || "", excerpt: article?.excerpt || "", slug: article?.slug || "", seoTitle: article?.seoTitle || "", seoDescription: article?.seoDescription || "", category: article?.category?._id || "" });
  const status = article?.status || "DRAFT"; const draftLike = status === "DRAFT" || status === "REJECTED";
  useEffect(() => { const unload = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; const navigate = (event: MouseEvent) => { if (dirty && event.target instanceof Element && event.target.closest("a[href]") && !window.confirm("Leave this page? Your unsaved changes will be lost.")) event.preventDefault(); }; window.addEventListener("beforeunload", unload); document.addEventListener("click", navigate, true); return () => { window.removeEventListener("beforeunload", unload); document.removeEventListener("click", navigate, true); }; }, [dirty]);
  const persist = useCallback(async (): Promise<{ id: string; revision: number } | null> => {
    const element = form.current; if (!element || !element.reportValidity()) return null;
    const data = new FormData(element);
    const result = await apiRequest(article ? `/api/articles/${article._id}` : "/api/articles", article ? "PATCH" : "POST", { ...Object.fromEntries(data), content, category: data.get("category") || null, tags: data.getAll("tags"), revision: article ? revision : undefined, coverAlt: alt });
    setDirty(false); setSavedRevision(result.revision ?? revision + 1);
    return { id: result.id!, revision: result.revision ?? revision + 1 };
  }, [article, alt, content, revision]);
  const done = useCallback((id: string, text: string) => { setMessage(text); if (!article) router.replace(`${base}/articles/${id}/edit`); router.refresh(); }, [article, base, router]);
  async function run(label: string, task: () => Promise<void>) { if (saving.current) return; saving.current = true; setBusy(label); setError(""); setMessage(""); try { await task(); } catch (e) { setError(e instanceof Error ? e.message : "Something went wrong"); } finally { saving.current = false; setBusy(""); } }
  const save = () => run("Saving…", async () => { const saved = await persist(); if (saved) done(saved.id, "Saved"); });
  const saveAnd = (action: "submit" | "publish") => run(action === "publish" ? "Publishing…" : "Submitting…", async () => {
    if (action === "publish" && !window.confirm("Publish this story now? It goes live immediately.")) return;
    const saved = await persist(); if (!saved) return;
    await apiRequest(`/api/articles/${saved.id}/workflow`, "POST", { action, revision: saved.revision });
    setSavedRevision(saved.revision + 1); done(saved.id, action === "publish" ? "Published — the story is live." : "Submitted for review. An editor will take it from here.");
  });
  const setCover = (file: File) => run("Uploading cover…", async () => {
    // Save first (also creates a new draft) so the upload uses the current revision.
    const saved = !article || dirty ? await persist() : { id: article._id, revision }; if (!saved) return;
    const description = alt.trim() || snap.title.trim(); if (!alt.trim()) setAlt(description);
    const result = await uploadCover(file, saved.id, saved.revision, description); setSavedRevision(result.revision); done(saved.id, "Cover image updated");
  });
  // Autosave drafts quietly; published stories are only changed on an explicit save.
  useEffect(() => { if (!article || !dirty || !draftLike) return; const timer = window.setTimeout(() => { if (saving.current) return; saving.current = true; persist().then(saved => { if (saved) { setMessage(`Draft autosaved at ${new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}`); router.refresh(); } }).catch(() => setMessage("Autosave paused — save manually.")).finally(() => { saving.current = false; }); }, 20000); return () => window.clearTimeout(timer); }, [article, dirty, draftLike, persist, router, content, snap]);
  useEffect(() => { const keys = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "s") { event.preventDefault(); void save(); } }; window.addEventListener("keydown", keys); return () => window.removeEventListener("keydown", keys); });
  const checks: [string, boolean][] = [["Headline of 8+ characters", snap.title.trim().length >= 8], ["Excerpt of 30+ characters", snap.excerpt.trim().length >= 30], ["Category chosen", Boolean(snap.category)], ["100+ characters of article text", textLength(content) >= 100], ["Cover image (recommended)", Boolean(article?.coverImage)]];
  const ready = checks.slice(0, 4).every(([, ok]) => ok);
  const previewTitle = (snap.seoTitle || snap.title || "Your headline appears here").slice(0, 70); const previewText = (snap.seoDescription || snap.excerpt || "Your excerpt or meta description appears here in search results.").slice(0, 170);
  return <form ref={form} className="editor-layout" onChange={event => { if (event.target instanceof HTMLInputElement && event.target.type === "file") return; setDirty(true); const data = new FormData(event.currentTarget); setSnap({ title: String(data.get("title") || ""), excerpt: String(data.get("excerpt") || ""), slug: String(data.get("slug") || ""), seoTitle: String(data.get("seoTitle") || ""), seoDescription: String(data.get("seoDescription") || ""), category: String(data.get("category") || "") }); }} onSubmit={event => { event.preventDefault(); void save(); }}>
    <div className="editor-main panel"><div className="editor-topline"><span className="eyebrow">YOUR STORY</span><Badge status={status} /></div><label>Article title<input className="title-input" name="title" defaultValue={article?.title} placeholder="Give your story a strong headline" required minLength={3} maxLength={200} /></label><label>Excerpt<textarea name="excerpt" defaultValue={article?.excerpt} placeholder="The essential idea, in a sentence or two. Shown on cards and in search results." maxLength={400} rows={3} /></label><label className="editor-label">Article body</label><RichEditor content={content} articleId={article?._id} onError={setError} onChange={html => { setContent(html); setDirty(true); }} />
      <div className="save-bar"><span className="muted small" role="status">{busy || (dirty ? "Unsaved changes · Ctrl+S to save" : message || "All changes saved")}</span><div className="actions"><button className="button secondary" disabled={Boolean(busy)}>{article ? "Save changes" : "Save draft"}</button>{!admin && draftLike ? <button type="button" className="button" disabled={Boolean(busy) || !ready} title={ready ? undefined : "Complete the checklist first"} onClick={() => void saveAnd("submit")}>{status === "REJECTED" ? "Save & resubmit" : "Save & submit for review"}</button> : null}{admin && !article?.deletedAt && status !== "PUBLISHED" ? <button type="button" className="button" disabled={Boolean(busy) || !ready} title={ready ? undefined : "Complete the checklist first"} onClick={() => void saveAnd("publish")}>{status === "SUBMITTED" ? "Approve & publish" : "Save & publish"}</button> : null}{admin && status === "PUBLISHED" ? <button type="button" className="button" disabled={Boolean(busy)} onClick={() => void save()}>Update live story</button> : null}</div></div>{error ? <p className="notice error" role="alert">{error}</p> : null}</div>
    <aside className="editor-settings"><div className="panel form-stack"><h3>Ready to {admin ? "publish" : "submit"}?</h3><ul className="checklist">{checks.map(([label, ok]) => <li key={label} className={ok ? "ok" : undefined}><span aria-hidden="true">{ok ? "✓" : "○"}</span>{label}<span className="sr-only">{ok ? " — done" : " — to do"}</span></li>)}</ul></div>
      <div className="panel form-stack"><h3>Story settings</h3><label>Category<select name="category" aria-label="Category" defaultValue={article?.category?._id || ""}><option value="">Choose a category</option>{categories.map(c => <option key={c._id} value={c._id}>{c.name}{!c.isActive ? " (inactive)" : ""}</option>)}</select></label><p className="small muted">Pick one of the main sections. Anything else appears under “Others”.</p><fieldset><legend>Tags</legend><div className="tag-options">{tags.map(tag => <label className="checkbox" key={tag._id}><input type="checkbox" name="tags" value={tag._id} defaultChecked={article?.tags.some(t => t._id === tag._id)} />{tag.name}</label>)}</div></fieldset><label>Slug<input name="slug" defaultValue={article?.slug} placeholder="Generated from your title" pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={120} /></label></div>
      <div className={`panel form-stack cover-drop${dragging ? " dragging" : ""}`} onDragOver={event => { if (event.dataTransfer.types.includes("Files")) { event.preventDefault(); setDragging(true); } }} onDragLeave={() => setDragging(false)} onDrop={event => { event.preventDefault(); setDragging(false); const file = event.dataTransfer.files[0]; if (file) void setCover(file); }}><h3>Cover image</h3>{article?.coverImage ? <Image className="cover-preview" src={article.coverImage.secureUrl} alt={article.coverImage.alt} width={600} height={340} sizes="300px" /> : <div className="image-empty">Drag an image here, or choose one below</div>}<label>Image description (alt text)<input value={alt} onChange={e => setAlt(e.target.value)} maxLength={250} placeholder="What does the image show?" /></label><label className="file-label">{article?.coverImage ? "Replace image" : "Choose image"}<input type="file" accept="image/*" disabled={Boolean(busy)} onChange={e => { const file = e.target.files?.[0]; if (file) void setCover(file); e.target.value = ""; }} /></label><p className="muted small">Large photos are resized automatically. {article ? "" : "Choosing an image saves your draft first."}</p>{article?.coverImage ? <button className="button danger secondary" type="button" disabled={Boolean(busy)} onClick={() => run("Removing cover…", async () => { if (!window.confirm("Remove this cover image?")) return; const saved = dirty ? await persist() : { id: article._id, revision }; if (!saved) return; const result = await apiRequest(`/api/articles/${article._id}/cover`, "DELETE", { revision: saved.revision }); setSavedRevision(result.revision ?? saved.revision + 1); done(article._id, "Cover image removed"); })}>Remove image</button> : null}</div>
      <details className="panel form-stack" open={!article}><summary>Search & social (SEO)</summary><div className="serp-preview" aria-label="Search result preview"><span className="serp-url">{siteHost} › article › {snap.slug || "your-story"}</span><strong className="serp-title">{previewTitle}</strong><span className="serp-text">{previewText}</span></div><label>SEO title <span className={`counter${snap.seoTitle.length > 60 ? " warn" : ""}`}>{snap.seoTitle.length}/70</span><input name="seoTitle" defaultValue={article?.seoTitle} maxLength={70} placeholder="Defaults to the headline · aim for 50–60 characters" /></label><label>Meta description <span className={`counter${snap.seoDescription.length > 160 ? " warn" : ""}`}>{snap.seoDescription.length}/170</span><textarea name="seoDescription" defaultValue={article?.seoDescription} maxLength={170} placeholder="Defaults to the excerpt · aim for 120–160 characters" /></label><label>Canonical URL<input name="canonicalUrl" type="url" defaultValue={article?.canonicalUrl} placeholder="Only if this story was first published elsewhere" /></label><label>Social image URL<input name="socialImage" type="url" defaultValue={article?.socialImage} placeholder="Defaults to the cover image" /></label></details><details className="panel form-stack"><summary>Source attribution</summary><label>Source name<input name="sourceName" defaultValue={article?.sourceName} maxLength={120} /></label><label>Source URL<input name="sourceUrl" type="url" defaultValue={article?.sourceUrl} /></label></details></aside>
  </form>;
}
