import { AnalyticsConsentPrompt } from "@/components/analytics-consent-prompt";
import type { Metadata } from "next";
import { cache } from "react";
import { notFound } from "next/navigation";
import Link from "next/link";
import mongoose from "mongoose";
import { publicArticle, listArticles } from "@/lib/queries";
import { siteUrl } from "@/lib/env";
import { safeJsonLd } from "@/lib/content";
import { ArticlePreview } from "@/components/article-preview";
import { ArticleCard } from "@/components/article-card";
import { AdSlot } from "@/components/ads/ad-slot";
import { ShareButtons, ViewTracker } from "@/components/article-interactions";
export const dynamic = "force-dynamic";
const getArticle = cache(publicArticle);
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const article = await getArticle((await params).slug); if (!article) return { title: "Article not found", robots: { index: false } }; const image = article.socialImage || article.coverImage?.secureUrl; const url = article.canonicalUrl || `${siteUrl()}/article/${article.slug}`; return { title: article.seoTitle || article.title, description: article.seoDescription || article.excerpt, alternates: { canonical: url }, openGraph: { type: "article", title: article.seoTitle || article.title, description: article.seoDescription || article.excerpt, url, publishedTime: article.publishedAt, modifiedTime: article.updatedAt, authors: [article.author.name], images: image ? [image] : [] }, twitter: { card: "summary_large_image", images: image ? [image] : [] } }; }
export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) { const article = await getArticle((await params).slug); if (!article) notFound(); const related = await listArticles({}, undefined, { _id: { $ne: new mongoose.Types.ObjectId(article._id) }, $or: [{ category: article.category ? new mongoose.Types.ObjectId(article.category._id) : null }, { tags: { $in: article.tags.map(t => new mongoose.Types.ObjectId(t._id)) } }] }); const url = `${siteUrl()}/article/${article.slug}`;
  const structured = { "@context": "https://schema.org", "@type": "NewsArticle", headline: article.title, description: article.excerpt, image: article.coverImage ? [article.coverImage.secureUrl] : [], datePublished: article.publishedAt, dateModified: article.updatedAt, author: { "@type": "Person", name: article.author.name, url: `${siteUrl()}/author/${article.author._id}` }, publisher: { "@type": "Organization", name: "SIGNAL", url: siteUrl() }, mainEntityOfPage: article.canonicalUrl || url };
  const crumbs = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteUrl() }, { "@type": "ListItem", position: 2, name: article.category?.name || "Latest", item: `${siteUrl()}${article.category ? `/category/${article.category.slug}` : "/latest"}` }, { "@type": "ListItem", position: 3, name: article.title, item: url }] };
  return <div className="container"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(structured) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(crumbs) }} /><ViewTracker id={article._id} /><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href={article.category ? `/category/${article.category.slug}` : "/latest"}>{article.category?.name || "Latest"}</Link></nav><AdSlot position="article-top" /><div className="public-article-layout"><div><ArticlePreview article={article} /><div className="article-after"><p className="small muted">Updated {new Date(article.updatedAt).toLocaleDateString("en", { timeZone: "UTC" })}</p><div className="tags">{article.tags.map(tag => <Link key={tag._id} href={`/tag/${tag.slug}`}>{tag.name}</Link>)}</div><ShareButtons title={article.title} /><AnalyticsConsentPrompt /><Link href={`/author/${article.author._id}`} className="author-box"><span className="avatar large">{article.author.name.slice(0, 1)}</span><span><strong>{article.author.name}</strong><p>{article.author.bio || "Contributor to SIGNAL."}</p><span className="text-link">More from this writer</span></span></Link></div></div><aside className="article-sidebar"><AdSlot position="sidebar" /><h3>Keep exploring</h3><Link className="text-link" href="/latest">Read the latest stories</Link></aside></div><AdSlot position="article-bottom" />{related.items.length ? <section className="related"><div className="section-heading editorial"><h2>The bigger picture</h2></div><div className="article-grid">{related.items.slice(0, 3).map(a => <ArticleCard key={a._id} article={a} />)}</div></section> : null}</div>;
}
