import Link from "next/link";
import { PublicShell } from "@/components/public-shell";
import { ArticleCard } from "@/components/article-card";
import { AdSlot } from "@/components/ads/ad-slot";
import { JsonLd } from "@/components/json-ld";
import { Empty } from "@/components/ui";
import { categoryBySlug, publicList, trendingArticles } from "@/lib/public-data";
import { navLinks, primaryCategories } from "@/lib/categories";
import { absolute, organization, site } from "@/lib/seo";
// Static with incremental regeneration; publishing refreshes it immediately (src/lib/revalidate.ts).
export const revalidate = 300;
async function sectionStories(slug: string) { const category = await categoryBySlug(slug); return category ? (await publicList({}, { category: category._id })).items.slice(0, 3) : []; }
export default async function Home() {
  const [latest, featured, popular, sections] = await Promise.all([publicList(), publicList({ featured: "true" }), trendingArticles(5), Promise.all(primaryCategories.map(async c => ({ ...c, items: await sectionStories(c.slug) })))]);
  const lead = featured.items[0] || latest.items[0]; const side = latest.items.filter(a => a._id !== lead?._id).slice(0, 3); const used = new Set([lead?._id, ...side.map(a => a._id)]); const feed = latest.items.filter(a => !used.has(a._id));
  const structured = { "@context": "https://schema.org", "@graph": [organization(), { "@type": "WebSite", "@id": absolute("/#website"), url: absolute("/"), name: site.name, description: site.description, publisher: { "@id": absolute("/#organization") }, inLanguage: "en", potentialAction: { "@type": "SearchAction", target: { "@type": "EntryPoint", urlTemplate: absolute("/search?q={search_term_string}") }, "query-input": "required name=search_term_string" } }] };
  return <PublicShell><JsonLd data={structured} /><div className="container home"><h1 className="sr-only">{site.name} — technology news and analysis</h1><div className="edition-line"><span className="eyebrow">THE TECHNOLOGY BRIEFING</span><span>{new Intl.DateTimeFormat("en", { dateStyle: "full", timeZone: "UTC" }).format(new Date())}</span></div>{lead ? <section className="hero-grid" aria-label="Top stories"><ArticleCard article={lead} featured /><div className="hero-side"><div className="section-label">ON OUR RADAR</div>{side.map(a => <article key={a._id}><Link className="eyebrow" href={a.category ? `/category/${a.category.slug}` : "/category/others"}>{a.category?.name || "Others"}</Link><h2><Link href={`/article/${a.slug}`}>{a.title}</Link></h2><p>{a.excerpt}</p><span className="small muted">{a.author?.name}</span></article>)}</div></section> : <section className="publication-empty"><span className="eyebrow">A CLEARER VIEW OF WHAT COMES NEXT</span><h2>Technology moves fast.<br />Perspective matters.</h2><p>Our newsroom is preparing its first stories. Explore the topics we cover, or return soon for the latest.</p><Link href="/latest" className="button">Explore the latest</Link></section>}<nav className="topic-strip" aria-label="Sections"><span>EXPLORE</span>{navLinks.slice(1).map(([href, label]) => <Link key={href} href={href}>{label}</Link>)}</nav><div className="home-feed"><section><div className="section-heading editorial"><h2>The latest</h2><Link className="text-link" href="/latest">All stories</Link></div>{feed.length ? <div className="article-grid two">{feed.map(a => <ArticleCard key={a._id} article={a} />)}</div> : <Empty title={latest.items.length ? "You're up to date." : "The next story is on its way."}>Fresh perspectives from the SIGNAL newsroom will appear here.</Empty>}</section><aside><div className="section-heading editorial"><h2>Most read</h2></div>{popular.length ? <ol className="popular-list">{popular.map((a, i) => <li key={a._id}><span>{String(i + 1).padStart(2, "0")}</span><div><span className="eyebrow">{a.category?.name || "Others"}</span><h3><Link href={`/article/${a.slug}`}>{a.title}</Link></h3></div></li>)}</ol> : <p className="muted">Discover what readers are following once our first stories go live.</p>}<AdSlot position="sidebar" /></aside></div><AdSlot position="home-feed" />{sections.filter(s => s.items.length).map(s => <section className="home-section" key={s.slug} aria-labelledby={`section-${s.slug}`}><div className="section-heading editorial"><h2 id={`section-${s.slug}`}><Link href={`/category/${s.slug}`}>{s.name}</Link></h2><Link className="text-link" href={`/category/${s.slug}`}>More {s.name}</Link></div><div className="article-grid">{s.items.map(a => <ArticleCard key={a._id} article={a} />)}</div></section>)}</div></PublicShell>;
}
