import Link from "next/link";
import { PublicShell } from "@/components/public-shell";
import { ArticleCard } from "@/components/article-card";
import { AdSlot } from "@/components/ads/ad-slot";
import { Empty } from "@/components/ui";
import { listArticles, taxonomies } from "@/lib/queries";
export const dynamic = "force-dynamic";
export default async function Home() {
  const [latest, featured, popular, taxonomy] = await Promise.all([listArticles(), listArticles({ featured: "true" }), listArticles({ sort: "views" }), taxonomies()]);
  const lead = featured.items[0] || latest.items[0]; const side = latest.items.filter(a => a._id !== lead?._id).slice(0, 3); const used = new Set([lead?._id, ...side.map(a => a._id)]); const feed = latest.items.filter(a => !used.has(a._id));
  return <PublicShell><div className="container home"><div className="edition-line"><span className="eyebrow">THE TECHNOLOGY BRIEFING</span><span>{new Intl.DateTimeFormat("en", { dateStyle: "full", timeZone: "UTC" }).format(new Date())}</span></div>{lead ? <section className="hero-grid" aria-label="Top stories"><ArticleCard article={lead} featured /><div className="hero-side"><div className="section-label">ON OUR RADAR</div>{side.map(a => <article key={a._id}><Link className="eyebrow" href={`/category/${a.category?.slug || "technology"}`}>{a.category?.name || "Technology"}</Link><h2><Link href={`/article/${a.slug}`}>{a.title}</Link></h2><p>{a.excerpt}</p><span className="small muted">{a.author?.name}</span></article>)}</div></section> : <section className="publication-empty"><span className="eyebrow">A CLEARER VIEW OF WHAT COMES NEXT</span><h1>Technology moves fast.<br />Perspective matters.</h1><p>Our newsroom is preparing its first stories. Explore the topics we cover, or return soon for the latest.</p><Link href="/latest" className="button">Explore the latest</Link></section>}<div className="topic-strip"><span>EXPLORE</span>{(taxonomy.categories.length ? taxonomy.categories : [{ _id: "ai", slug: "ai", name: "AI" }, { _id: "programming", slug: "programming", name: "Programming" }, { _id: "gadgets", slug: "gadgets", name: "Gadgets" }, { _id: "startups", slug: "startups", name: "Startups" }]).slice(0, 9).map(c => <Link key={c._id} href={`/category/${c.slug}`}>{c.name}</Link>)}</div><div className="home-feed"><section><div className="section-heading editorial"><h2>The latest</h2><Link className="text-link" href="/latest">All stories</Link></div>{feed.length ? <div className="article-grid two">{feed.map(a => <ArticleCard key={a._id} article={a} />)}</div> : <Empty title={latest.items.length ? "You're up to date." : "The next story is on its way."}>Fresh perspectives from the SIGNAL newsroom will appear here.</Empty>}</section><aside><div className="section-heading editorial"><h2>Most read</h2></div>{popular.items.length ? <ol className="popular-list">{popular.items.slice(0, 5).map((a, i) => <li key={a._id}><span>{String(i + 1).padStart(2, "0")}</span><div><span className="eyebrow">{a.category?.name}</span><h3><Link href={`/article/${a.slug}`}>{a.title}</Link></h3></div></li>)}</ol> : <p className="muted">Discover what readers are following once our first stories go live.</p>}<AdSlot position="sidebar" /></aside></div><AdSlot position="home-feed" /></div></PublicShell>;
}
