import { GeographyPanel } from "./geography-panel";
import Link from "next/link";
import { analytics, rangePresets, type SeriesPoint } from "@/lib/analytics";
import { ViewsChart } from "./views-chart";
import type { Actor } from "@/lib/permissions";
import type { SearchParams } from "@/types";
import { Empty, Stat, formatNumber } from "./ui";
function Bars({ data, label }: { data: SeriesPoint[]; label: string }) { const max = Math.max(1, ...data.map(d => d.count)); return data.length ? <div className="bar-chart" role="img" aria-label={label}>{data.map(point => <div className="bar-row" key={point._id}><span>{point._id.toLowerCase()}</span><div><span style={{ width: `${Math.max(2, point.count / max * 100)}%` }} /></div><strong>{formatNumber(point.count)}</strong></div>)}</div> : <Empty title="No data in this period." />; }
export async function AnalyticsPanel({ actor, params, author }: { actor: Actor; params: SearchParams; author?: string }) {
  const data = await analytics(actor, params, author); const base = actor.role === "ADMIN" ? "/admin" : "/writer";
  return <><GeographyPanel actor={actor} params={author ? params : {}} scope={author ? { author } : {}} summary={!author} /><div className="range-presets" role="group" aria-label="Quick periods">{rangePresets().map(r => <Link key={r.label} className={`chip${data.from === r.from && data.to === r.to ? " active" : ""}`} href={`?from=${r.from}&to=${r.to}`} scroll={false}>{r.label}</Link>)}</div><form className="filters"><label>From · UTC<input type="date" name="from" defaultValue={data.from} /></label><label>Through · UTC<input type="date" name="to" defaultValue={data.to} min={data.from} /></label><button className="button secondary">Update period</button></form><div className="stats-grid compact"><Stat label="Views in selected period" value={data.totalViews} detail={`${formatNumber(Math.round(data.totalViews / Math.max(1, data.views.length)))} per day on average`} /><Stat label="First publications in period" value={data.publishing.reduce((n, p) => n + p.count, 0)} /><Stat label="Articles · all time" value={data.statuses.reduce((n, p) => n + p.count, 0)} /></div><section className="panel"><h2>Views over time <small>Daily · UTC</small></h2>{data.totalViews ? <ViewsChart data={data.views} /> : <Empty title="No views in this period yet.">Views are counted when readers allow article analytics.</Empty>}</section><div className="two-column"><section className="panel"><h2>Publishing activity</h2><Bars data={data.publishing} label="First publications per day, UTC" /></section><section className="panel"><h2>Status distribution <small>All time</small></h2><Bars data={data.statuses} label="Articles by current status" /></section><section className="panel"><h2>Articles by category <small>All time</small></h2><Bars data={data.categories} label="Articles by category" /><h3>Category views · all time</h3><Bars data={data.categories.map(c => ({ _id: c._id, count: c.views }))} label="Views by category" /></section></div><section className="panel"><h2>Top articles <small>Selected period</small></h2>{data.topArticles.length ? <ol className="ranking">{data.topArticles.map(a => <li key={String(a._id)}><Link href={`${base}/articles/${a._id}/edit`}>{a.title}</Link><strong>{formatNumber(a.count)} views</strong></li>)}</ol> : <Empty title="Article views will appear here." />}</section>{actor.role === "ADMIN" && !author ? <section className="panel"><h2>Writer performance <small>All time</small></h2><div className="table-scroll"><table><thead><tr><th>Writer</th><th>Articles</th><th>Published</th><th>Views</th></tr></thead><tbody>{data.leaderboard.map(w => <tr key={String(w._id)}><td><Link href={`/admin/writers/${w._id}`}>{w.name}</Link></td><td>{w.count}</td><td>{w.published}</td><td>{formatNumber(w.views)}</td></tr>)}</tbody></table></div><h3>Most published writers</h3><Bars data={data.leaderboard.toSorted((a, b) => b.published - a.published).map(w => ({ _id: w.name, count: w.published }))} label="Published articles by writer" /></section> : null}</>;
}
