import { GeographyPanel } from "./geography-panel";
import Link from "next/link";
import { notFound } from "next/navigation";
import { User, AuditLog } from "@/models";
import { dashboardStats, listArticles, privateArticle, scalar, taxonomies, pageNumber } from "@/lib/queries";
import { listWriters } from "@/lib/analytics";
import { objectId } from "@/lib/validation";
import { editableStatuses, type Actor } from "@/lib/permissions";
import { serialize, type AuditRecord, type Person, type SearchParams } from "@/types";
import { ArticleTable, Timeline } from "./article-table";
import { ArticleFilters } from "./article-filters";
import { AnalyticsPanel } from "./analytics-panel";
import { ArticleEditor } from "./editor/article-editor";
import { ArticlePreview } from "./article-preview";
import { WorkflowControls } from "./workflow-controls";
import { ActionButton, DataForm } from "./client-forms";
import { TaxonomyManager, WriterForm } from "./management-forms";
import { Badge, Empty, formatDate, formatNumber, Pagination, Stat } from "./ui";
export function PageHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div>{children}</div>; }
export async function DashboardPage({ actor, path, params }: { actor: Actor; path: string[]; params: SearchParams }) {
  const admin = actor.role === "ADMIN"; const base = admin ? "/admin" : "/writer"; const route = path[0] || "";
  if (!route) {
    const stats = await dashboardStats(actor);
    const [recent, submitted, published] = await Promise.all([listArticles({ sort: "updated" }, actor), admin ? listArticles({ status: "SUBMITTED" }, actor) : Promise.resolve(null), admin ? listArticles({ status: "PUBLISHED" }, actor) : Promise.resolve(null)]);
    return <><PageHeading eyebrow={admin ? "THE NEWSROOM AT A GLANCE" : "YOUR NEXT STORY STARTS HERE"} title={admin ? "Editorial overview" : `Welcome, ${actor.name.split(" ")[0]}.`}><Link className="button" href={`${base}/articles/new`}>Create article</Link></PageHeading><div className="stats-grid"><Stat label="Total articles" value={stats.total} /><Stat label="Total views" value={stats.views} />{admin ? <><Stat label="Writers" value={stats.writers} /><Stat label="Active writers" value={stats.activeWriters} /></> : null}{["DRAFT", "SUBMITTED", "APPROVED", "PUBLISHED", "REJECTED"].map(status => <Stat key={status} label={status.toLowerCase()} value={stats.counts.find(c => c._id === status)?.count || 0} />)}</div><section className="panel"><div className="section-heading"><h2>Recently updated</h2><Link href={`${base}/articles`} className="text-link">All articles</Link></div><ArticleTable articles={recent.items.slice(0, 5)} base={base} /></section>{admin ? <div className="two-column"><section className="panel"><h2>Awaiting review</h2>{submitted?.items.length ? submitted.items.slice(0, 4).map(a => <Link className="story-row" key={a._id} href={`${base}/articles/${a._id}/edit`}><strong>{a.title}</strong><span className="small muted">{a.author.name} · Submitted {formatDate(a.submittedAt)}</span></Link>) : <Empty title="No articles submitted for review." />}</section><section className="panel"><h2>Recent publications</h2>{published?.items.length ? published.items.slice(0, 4).map(a => <Link className="story-row" key={a._id} href={`/article/${a.slug}`}><strong>{a.title}</strong><span className="small muted">Published {formatDate(a.publishedAt)}</span></Link>) : <Empty title="No published articles yet." />}</section></div> : null}<section className="panel"><h2>Top articles</h2><ArticleTable articles={stats.top} base={base} /></section>{admin ? <><section className="panel"><h2>Recent activity</h2><Timeline events={stats.activity} /></section><AnalyticsPanel actor={actor} params={{}} /></> : null}</>;
  }
  if (route === "articles" && path[1] === "new" && path.length === 2) { const taxonomy = await taxonomies(); return <><PageHeading eyebrow="CREATE ARTICLE" title="A new perspective." /><ArticleEditor {...taxonomy} base={base} /></>; }
  if (route === "articles" && path[1] && ["edit", "preview"].includes(path[2]) && path.length === 3) {
    if (!objectId.safeParse(path[1]).success) notFound();
    let data; try { data = await privateArticle(actor, path[1]); } catch (error) { if (error instanceof Error && "status" in error && (error.status === 403 || error.status === 404)) notFound(); throw error; }
    const { article, history } = data; const taxonomy = await taxonomies(false);
    if (path[2] === "preview") return <><div className="notice">Private preview · <Link className="text-link" href={`${base}/articles/${article._id}/edit`}>Back to editor</Link></div><ArticlePreview article={article} /></>;
    return <><PageHeading eyebrow="ARTICLE WORKSPACE" title={article.status === "SUBMITTED" && admin ? "Review this story" : "Shape your story"}><Link className="button secondary" href={`${base}/articles/${article._id}/preview`}>Preview saved article</Link></PageHeading>{article.rejectionReason ? <div className="notice error"><strong>Revision requested</strong><p>{article.rejectionReason}</p></div> : null}<WorkflowControls article={article} admin={admin} />{!article.deletedAt && (admin || editableStatuses.includes(article.status)) ? <ArticleEditor article={article} {...taxonomy} base={base} /> : <ArticlePreview article={article} />}<section className="panel"><h2>Article performance</h2><div className="stats-grid compact"><Stat label="Views" value={article.views} /><Stat label="Status" value={article.status.toLowerCase()} /><Stat label="Published" value={formatDate(article.publishedAt)} /></div></section><GeographyPanelSlot actor={actor} params={params} articleId={article._id} published={article.status === "PUBLISHED"} /><details className="panel"><summary>Article history · latest 100 events</summary><Timeline events={history} /></details></>;
  }
  if ((route === "articles" || (admin && route === "review")) && path.length === 1) {
    const review = route === "review"; const filters = review ? { ...params, status: "SUBMITTED" } : params;
    const [result, taxonomy, writers] = await Promise.all([listArticles(filters, actor), taxonomies(false), admin ? User.find({ role: "WRITER" }).select("name").sort({ name: 1 }).limit(500).lean() : Promise.resolve(undefined)]);
    return <><PageHeading eyebrow={review ? "EDITORIAL REVIEW" : "CONTENT LIBRARY"} title={review ? "Review queue" : admin ? "All articles" : "My articles"}><Link href={`${base}/articles/new`} className="button">Create article</Link></PageHeading><section className="panel"><ArticleFilters params={params} categories={taxonomy.categories} writers={writers ? serialize<Person[]>(writers) : undefined} review={review} /><p className="small muted">{result.total} articles</p><ArticleTable articles={result.items} base={base} /><Pagination {...result} params={params} /></section></>;
  }
  if (route === "analytics" && path[1] === "geography" && path.length === 2) return <><PageHeading eyebrow="COUNTRY AUDIENCE" title="Geographic Analytics" /><GeographyPanel actor={actor} params={params} /></>;
  if (route === "analytics" && path.length === 1) return <><PageHeading eyebrow="READERSHIP & PUBLISHING" title={admin ? "Publication analytics" : "My article analytics"} /><AnalyticsPanel actor={actor} params={params} /></>;
  if ((route === "profile" || (admin && route === "settings")) && path.length === 1) {
    const user = await User.findById(actor.id).lean();
    return <><PageHeading eyebrow="YOUR ACCOUNT" title="Profile & security" /><div className="panel narrow"><DataForm url="/api/profile" method="PATCH"><label>Name<input name="name" defaultValue={actor.name} required minLength={2} maxLength={100} /></label><label>Email<input value={actor.email} readOnly /></label><label>Bio<textarea name="bio" defaultValue={user?.bio} maxLength={1000} /></label><h3>Change password</h3><p className="small muted">Leave these blank to keep your password. Changing it signs out all sessions.</p><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" /></label><label>New password<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} /></label></DataForm></div></>;
  }
  if (admin && (route === "categories" || route === "tags") && path.length === 1) { const data = await taxonomies(false); return <><PageHeading eyebrow="ORGANIZE THE PUBLICATION" title={route === "categories" ? "Categories" : "Tags"} /><TaxonomyManager kind={route} items={data[route]} /></>; }
  if (admin && route === "writers" && !path[1]) {
    const result = await listWriters(params);
    return <><PageHeading eyebrow="THE PEOPLE BEHIND THE STORIES" title="Writers" /><WriterForm /><section className="panel"><form className="filters"><label className="search-field">Search<input name="q" defaultValue={scalar(params.q)} placeholder="Name or email" /></label><label>Status<select name="status" defaultValue={scalar(params.status)}><option value="">All writers</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label>Sort<select name="sort" defaultValue={scalar(params.sort)}><option value="">Newest</option><option value="name">Name</option><option value="views">Most views</option></select></label><button className="button secondary">Apply</button></form>{result.items.length ? <div className="table-scroll"><table><thead><tr><th>Writer</th><th>Status</th><th>Articles</th><th>Published</th><th>Submitted</th><th>Rejected</th><th>Views</th><th>Last sign-in / joined</th><th>Actions</th></tr></thead><tbody>{result.items.map(w => <tr key={String(w._id)}><td><Link className="table-title" href={`/admin/writers/${w._id}`}>{w.name}</Link><p className="small muted">{w.email}</p></td><td><Badge status={w.isActive ? "ACTIVE" : "INACTIVE"} /></td><td>{w.stats?.total || 0}</td><td>{w.stats?.published || 0}</td><td>{w.stats?.submitted || 0}</td><td>{w.stats?.rejected || 0}</td><td>{formatNumber(w.stats?.views || 0)}</td><td className="small">{formatDate(w.lastLoginAt)}<br />{formatDate(w.createdAt)}</td><td><ActionButton url={`/api/admin/writers/${w._id}`} method="PATCH" data={{ isActive: !w.isActive }} confirm={`${w.isActive ? "Deactivate" : "Activate"} ${w.name}?`}>{w.isActive ? "Deactivate" : "Activate"}</ActionButton></td></tr>)}</tbody></table></div> : <Empty title="No writers match these filters." />}<Pagination {...result} params={params} /></section></>;
  }
  if (admin && route === "writers" && path[1] && path.length === 2) {
    if (!objectId.safeParse(path[1]).success) notFound(); const writer = await User.findOne({ _id: path[1], role: "WRITER" }).lean(); if (!writer) notFound();
    const [stats, articles, taxonomy, lastActivity] = await Promise.all([dashboardStats(actor, path[1]), listArticles({ ...params, author: path[1] }, actor), taxonomies(false), AuditLog.findOne({ actorId: writer._id }).sort({ createdAt: -1 }).lean()]);
    return <><PageHeading eyebrow="WRITER PERFORMANCE" title={writer.name}><Badge status={writer.isActive ? "ACTIVE" : "INACTIVE"} /></PageHeading><section className="panel writer-profile"><span className="avatar large">{writer.name.slice(0, 1)}</span><div><p>{writer.email}</p><p>{writer.bio || "No biography added."}</p><p className="small muted">Joined {formatDate(writer.createdAt)} · Last activity {formatDate(lastActivity?.createdAt)} · Last sign-in {formatDate(writer.lastLoginAt)}</p></div><ActionButton url={`/api/admin/writers/${writer._id}`} method="PATCH" data={{ isActive: !writer.isActive }} confirm="Change this writer's account status?">{writer.isActive ? "Deactivate account" : "Activate account"}</ActionButton></section><div className="stats-grid"><Stat label="Total articles" value={stats.total} /><Stat label="Total views" value={stats.views} />{["DRAFT", "SUBMITTED", "APPROVED", "PUBLISHED", "REJECTED"].map(s => <Stat key={s} label={s.toLowerCase()} value={stats.counts.find(c => c._id === s)?.count || 0} />)}</div><section className="panel"><h2>Articles</h2><ArticleFilters params={params} categories={taxonomy.categories} /><ArticleTable articles={articles.items} base="/admin" /><Pagination {...articles} params={params} /></section><AnalyticsPanel actor={actor} params={params} author={path[1]} /></>;
  }
  if (admin && route === "activity" && path.length === 1) { const page = pageNumber(params.page); const [events, total] = await Promise.all([AuditLog.find().populate("actorId", "name").sort({ createdAt: -1 }).skip((page - 1) * 30).limit(30).lean(), AuditLog.countDocuments()]); return <><PageHeading eyebrow="ACCOUNTABILITY & HISTORY" title="Editorial activity" /><section className="panel"><Timeline events={serialize<AuditRecord[]>(events)} /><Pagination page={page} pages={Math.max(1, Math.ceil(total / 30))} params={params} /></section></>; }
  notFound();
}

function GeographyPanelSlot({ actor, params, articleId, published }: { actor: Actor; params: SearchParams; articleId: string; published: boolean }) { return actor.role === "ADMIN" || published ? <GeographyPanel actor={actor} params={params} scope={{ article: articleId }} /> : null; }
