import Link from "next/link";
import { Activity, FileText, LayoutDashboard, Users, Tags, Folder, ClipboardCheck, PenLine, UserRound, Settings } from "lucide-react";
import type { Actor } from "@/lib/permissions";
import { Logout } from "./client-forms";
const adminLinks = [["", "Overview", LayoutDashboard], ["articles", "Articles", FileText], ["review", "Review queue", ClipboardCheck], ["writers", "Writers", Users], ["categories", "Categories", Folder], ["tags", "Tags", Tags], ["analytics", "Analytics", Activity], ["analytics/geography", "Geographic Analytics", Activity], ["activity", "Activity", Activity], ["settings", "Settings", Settings]] as const;
const writerLinks = [["", "Overview", LayoutDashboard], ["articles", "My articles", FileText], ["articles/new", "Create article", PenLine], ["analytics", "Analytics", Activity], ["analytics/geography", "Geographic Analytics", Activity], ["profile", "Profile", UserRound]] as const;
export function DashboardShell({ actor, path, children }: { actor: Actor; path: string; children: React.ReactNode }) {
  const base = actor.role === "ADMIN" ? "/admin" : "/writer";
  return <div className="dashboard"><aside className="sidebar"><Link href="/" className="wordmark">SIGNAL<span>▰</span></Link><span className="sidebar-label">{actor.role === "ADMIN" ? "EDITORIAL OPERATIONS" : "WRITER WORKSPACE"}</span><nav aria-label="Workspace navigation">{(actor.role === "ADMIN" ? adminLinks : writerLinks).map(([route, label, Icon]) => <Link key={route} href={`${base}/${route}`} className={path === route ? "active" : ""} aria-current={path === route ? "page" : undefined}><Icon size={18} />{label}</Link>)}</nav><div className="sidebar-bottom"><Link href="/">View publication</Link><div className="account"><span className="avatar">{actor.name.slice(0, 1)}</span><div><strong>{actor.name}</strong><small>{actor.role.toLowerCase()}</small></div></div><Logout /></div></aside><div className="workspace"><header className="workspace-header"><span>Newsroom <span className="muted">/ {path.split("/")[0] || "Overview"}</span></span><span className="small muted">Your editorial workspace</span></header><main id="main" className="workspace-main">{children}</main></div></div>;
}
