"use client";
import { useState } from "react";
import type { Taxonomy } from "@/types";
import { ActionButton, DataForm } from "./client-forms";
export function WriterForm() { return <details className="panel"><summary>Create writer account</summary><DataForm url="/api/admin/writers" label="Create writer"><div className="form-grid"><label>Full name<input name="name" required minLength={2} maxLength={100} /></label><label>Email<input type="email" name="email" required /></label><label>Initial password<input type="password" name="password" required minLength={12} maxLength={128} autoComplete="new-password" /></label><label>Bio<textarea name="bio" maxLength={1000} /></label></div><p className="small muted">Share the initial password securely. The writer can change it from Profile.</p></DataForm></details>; }
export function TaxonomyManager({ kind, items }: { kind: "categories" | "tags"; items: Taxonomy[] }) {
  const [editing, setEditing] = useState<Taxonomy | null>(null);
  return <div className="management-grid"><section className="panel"><h2>{editing ? `Edit ${editing.name}` : `New ${kind === "categories" ? "category" : "tag"}`}</h2><DataForm key={editing?._id || "new"} url={`/api/admin/${kind}${editing ? `/${editing._id}` : ""}`} method={editing ? "PATCH" : "POST"} transform={data => ({ ...data, isActive: data.isActive === "on" })} onSaved={() => setEditing(null)}><label>Name<input name="name" defaultValue={editing?.name} required minLength={2} maxLength={60} /></label><label>Slug<input name="slug" defaultValue={editing?.slug} placeholder="Generated from name" /></label><label>Description<textarea name="description" defaultValue={editing?.description} maxLength={500} /></label><label className="checkbox"><input type="checkbox" name="isActive" defaultChecked={editing?.isActive ?? true} />Active</label></DataForm>{editing ? <button className="button secondary" onClick={() => setEditing(null)}>Cancel edit</button> : null}</section><section className="panel"><h2>All {kind}</h2>{!items.length ? <p className="muted">No {kind} yet.</p> : <div className="taxonomy-list">{items.map(item => <div key={item._id}><div><strong>{item.name}</strong><p className="small muted">/{item.slug} · {item.isActive ? "Active" : "Inactive"}</p><p className="small">{item.description}</p></div><div className="actions"><button className="button secondary" onClick={() => setEditing(item)}>Edit</button><ActionButton url={`/api/admin/${kind}/${item._id}`} method="DELETE" confirm={`Delete ${item.name}? This is only possible when no articles use it.`} className="button secondary danger">Delete</ActionButton></div></div>)}</div>}</section></div>;
}
